"""
StyleForge train_one_style.py — Prepare dataset + config for single-style LoRA training.

Uses AI Toolkit (ostris/ai-toolkit) to train a LoRA on FLUX.2 Klein 4B.

Workflow:
  1. Read style_map.json → get images for target style
  2. Copy images to data/datasets/{style_name}/
  3. Generate .txt caption files with trigger word
  4. Generate AI Toolkit TOML config
  5. Print the training command (or run it directly with --run)
"""

import argparse
import json
import os
import shutil
import sys
import textwrap
from pathlib import Path


def _sanitize(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_").strip("_")


def build_dataset(
    style_name: str,
    trigger_word: str,
    style_map: dict,
    image_dir: Path,
    dataset_dir: Path,
    dry_run: bool = False,
) -> int:
    """Copy images belonging to a style into a training dataset directory."""
    dataset_dir.mkdir(parents=True, exist_ok=True)

    matched = []
    for img_rel, meta in style_map.items():
        sname = meta.get("style_name", "")
        cid = meta.get("cluster_id", "")
        # Match by style_name or cluster_id
        if _sanitize(sname) == _sanitize(style_name) or str(cid) == style_name:
            src = image_dir / Path(img_rel).name
            if src.exists():
                matched.append((src, img_rel))

    if not matched:
        # Try fuzzy: check if any style_name contains the query
        for img_rel, meta in style_map.items():
            sname = meta.get("style_name", "")
            if _sanitize(style_name) in _sanitize(sname):
                src = image_dir / Path(img_rel).name
                if src.exists():
                    matched.append((src, img_rel))

    if not matched:
        print(f"No images found for style: {style_name}")
        print(f"Available styles: {sorted(set(m.get('style_name', '?') for m in style_map.values()))}")
        sys.exit(1)

    print(f"Found {len(matched)} images for style '{style_name}'")

    if dry_run:
        return len(matched)

    for i, (src, _) in enumerate(matched):
        dst_img = dataset_dir / f"img_{i:04d}.png"
        dst_txt = dataset_dir / f"img_{i:04d}.txt"
        shutil.copy2(src, dst_img)
        dst_txt.write_text(f"{trigger_word}, high quality artwork", encoding="utf-8")

    print(f"  Dataset ready: {dataset_dir}  ({len(matched)} images + captions)")
    return len(matched)


def generate_config(
    style_name: str,
    trigger_word: str,
    dataset_dir: Path,
    output_dir: Path,
    base_model: str,
    rank: int = 8,
    learning_rate: float = 1e-4,
    total_steps: int = 1500,
) -> Path:
    """Generate an AI Toolkit TOML configuration file."""
    output_dir.mkdir(parents=True, exist_ok=True)

    config = textwrap.dedent(f"""\
    # StyleForge LoRA training config — {style_name}
    # Generated by train_one_style.py

    [training]
    batch_size = 1
    steps = {total_steps}
    gradient_accumulation_steps = 1

    [model]
    name = "flux_2_klein"
    base_model = "{base_model}"
    precision = "fp8"

    [adapter]
    type = "lora"
    rank = {rank}
    alpha = {rank}

    [optimizer]
    name = "adafactor"
    learning_rate = {learning_rate}
    warmup_steps = 100

    [dataset]
    path = "{dataset_dir.as_posix()}"
    resolution = [1024]
    bucket_training = true

    [output]
    path = "{output_dir.as_posix()}"
    name = "style_{_sanitize(style_name)}"
    save_every = 100
    """)

    config_path = output_dir / f"config_{_sanitize(style_name)}.toml"
    config_path.write_text(config, encoding="utf-8")
    print(f"  Config: {config_path}")
    return config_path


def main():
    parser = argparse.ArgumentParser(description="StyleForge single-style LoRA trainer")
    parser.add_argument("style", help="Style name or cluster ID (e.g. 'style_03' or 'flat_cel')")
    parser.add_argument("--trigger-word", default=None, help="Trigger word (default: style name)")
    parser.add_argument("--rank", type=int, default=8, help="LoRA rank (default: 8)")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate (default: 1e-4)")
    parser.add_argument("--steps", type=int, default=1500, help="Total training steps")
    parser.add_argument("--base-model", default="models/flux-2-klein-4b.safetensors",
                        help="Path to FLUX.2 Klein 4B base model")
    parser.add_argument("--run", action="store_true", help="Launch training after prep")
    parser.add_argument("--dry-run", action="store_true", help="Only count images, don't copy")
    parser.add_argument("--project-root", default=None, help="Project root")
    args = parser.parse_args()

    if args.project_root:
        root = Path(args.project_root)
    else:
        root = Path(__file__).resolve().parent.parent

    style_map_path = root / "clustering" / "style_map.json"
    if not style_map_path.exists():
        print(f"style_map.json not found at {style_map_path}")
        print("Run cluster.py first.")
        sys.exit(1)

    style_map = json.loads(style_map_path.read_text(encoding="utf-8"))
    trigger = args.trigger_word or _sanitize(args.style)

    image_dir = root / "data" / "standardized"
    dataset_dir = root / "data" / "datasets" / _sanitize(args.style)
    output_dir = root / "loras"

    # Step 1: Build dataset
    n_images = build_dataset(args.style, trigger, style_map, image_dir, dataset_dir, dry_run=args.dry_run)
    if args.dry_run:
        return

    # Step 2: Adjust steps to dataset size
    total_steps = args.steps if args.steps else max(n_images * 100, 500)

    # Step 3: Generate config
    config_path = generate_config(
        style_name=args.style,
        trigger_word=trigger,
        dataset_dir=dataset_dir,
        output_dir=output_dir,
        base_model=args.base_model,
        rank=args.rank,
        learning_rate=args.lr,
        total_steps=total_steps,
    )

    # Step 4: Print command or run
    cmd = f"ai-toolkit train --config {config_path}"
    print(f"\n{'='*60}")
    if args.run:
        print(f"Launching: {cmd}")
        os.system(cmd)
    else:
        print(f"Ready. Run manually:")
        print(f"  {cmd}")
        print(f"\nTip: Use --run to launch training directly.")


if __name__ == "__main__":
    main()
